name: rfbuilder_app
description: EmserApp

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  simple_animations: 1.3.3       
  iconsax: ^0.0.8
  get: ^4.3.8
  flutter_launcher_icons: ^0.9.2
  getwidget: ^2.0.4
  flutter_advanced_drawer: ^1.2.3+1
  animate_do: ^2.0.0
  flutter_rounded_date_picker: ^2.0.2
  provider: ^6.0.1
  flutter_barcode_scanner: ^2.0.0
  permission_handler: ^5.0.1
  flutter_verification_code: ^1.1.0
  introduction_screen: ^2.1.0
  flutter_animation_progress_bar: ^2.0.1
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  fl_chart: ^0.40.2
  google_fonts: ^2.1.0
  easy_localization: ^3.0.0
  flutter_svg: ^0.23.0+1
  sound_stream: ^0.3.0
  dialogflow_grpc: ^0.2.9
  rxdart: ^0.27.3
  kommunicate_flutter: ^1.3.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
    generate: true
    uses-material-design: true

    fonts:
    - family: CircularStd
      fonts:
      - asset: assets/fonts/circularstd.ttf

    assets:
        - assets/images/
        - assets/credentials.json
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/icon.png"
  

flutter_intl:
  enabled: true
  generate: true
  main_locale: en
  class_name: S



